version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: getalife
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Main Backend API
  main_backend:
    build: ./main_backend
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=getalife
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_HOST=postgres
      - DB_PORT=5432
      - ML_SERVICE_URL=http://ml_service:8000
      - EMAIL_ADDRESS=your_email@gmail.com
      - EMAIL_PASSWORD=your_app_password
      - JWT_SECRET_KEY=your_secret_key
    depends_on:
      postgres:
        condition: service_healthy
      ml_service:
        condition: service_started
    volumes:
      - ./main_backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # ML Service
  ml_service:
    build: ./ml_service
    ports:
      - "8001:8000"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./ml_service:/app
      - ml_models:/app/chroma_db
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
  ml_models:
